<?php
    return [
      [
        'name' => 'SavedSearch_Field_Lookup_Groups',
        'entity' => 'SavedSearch',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
          'version' => 4,
          'values' => [
            'name' => 'Field_Lookup_Groups',
            'label' => 'Field Lookup Groups',
            'form_values' => NULL,
            'search_custom_id' => NULL,
            'api_entity' => 'FieldLookupGroup',
            'api_params' => [
              'version' => 4,
              'select' => [
                'name',
                'lookup_type:label',
                'lookup_operator:label',
                'field_1_entity:label',
                'field_1_name',
                'field_2_entity:label',
                'field_2_name',
              ],
              'orderBy' => [],
              'where' => [],
              'groupBy' => [],
              'join' => [],
              'having' => [],
            ],
            'expires_date' => NULL,
            'description' => NULL,
            'mapping_id' => NULL,
          ],
        ],
      ],
      [
        'name' => 'SavedSearch_Field_Lookup_Groups_SearchDisplay_Field_Lookup_Groups_Table_1',
        'entity' => 'SearchDisplay',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
          'version' => 4,
          'values' => [
            'name' => 'Field_Lookup_Groups_Table_1',
            'label' => 'Field Lookup Groups Table 1',
            'saved_search_id.name' => 'Field_Lookup_Groups',
            'type' => 'table',
            'settings' => [
              'actions' => TRUE,
              'limit' => 25,
              'classes' => [
                'table',
                'table-striped',
              ],
              'pager' => [],
              'placeholder' => 5,
              'sort' => [
                [
                  'id',
                  'ASC',
                ],
              ],
              'columns' => [
                [
                  'type' => 'field',
                  'key' => 'name',
                  'dataType' => 'String',
                  'label' => 'Name',
                  'sortable' => TRUE,
                  'editable' => TRUE,
                  'cssRules' => [
                    [
                      'font-bold',
                      'name',
                      'IS NOT EMPTY',
                    ],
                  ],
                ],
                [
                  'type' => 'field',
                  'key' => 'lookup_type:label',
                  'dataType' => 'String',
                  'label' => 'Lookup Type',
                  'sortable' => TRUE,
                  'editable' => TRUE,
                ],
                [
                  'type' => 'field',
                  'key' => 'lookup_operator:label',
                  'dataType' => 'String',
                  'label' => 'Lookup Operator',
                  'sortable' => TRUE,
                  'editable' => TRUE,
                ],
                [
                  'type' => 'field',
                  'key' => 'field_1_entity:label',
                  'dataType' => 'String',
                  'label' => 'Field 1 Entity',
                  'sortable' => TRUE,
                  'editable' => TRUE,
                ],
                [
                  'type' => 'field',
                  'key' => 'field_1_name',
                  'dataType' => 'String',
                  'label' => 'Field 1 Name',
                  'sortable' => TRUE,
                  'editable' => TRUE,
                ],
                [
                  'type' => 'field',
                  'key' => 'field_2_entity:label',
                  'dataType' => 'String',
                  'label' => 'Field 2 Entity',
                  'sortable' => TRUE,
                  'editable' => TRUE,
                ],
                [
                  'type' => 'field',
                  'key' => 'field_2_name',
                  'dataType' => 'String',
                  'label' => 'Field 2 Name',
                  'sortable' => TRUE,
                  'editable' => TRUE,
                ],
                [
                  'links' => [
                    [
                      'path' => 'civicrm/field-lookups#?fgid=[id]',
                      'icon' => 'fa-list',
                      'text' => 'Edit Field Lookups',
                      'style' => 'default',
                      'condition' => [],
                      'entity' => '',
                      'action' => '',
                      'join' => '',
                    ],
                  ],
                  'type' => 'links',
                  'alignment' => 'text-right',
                ],
              ],
              'cssRules' => [],
            ],
            'acl_bypass' => FALSE,
          ],
        ],
      ],
    ];
